### ISSUE TITLE
Version conflict while installing click for Tabulo

### ISSUE THREAD

**Issue by gurjotcrossml** [interviewBubble/Tabulo#25]
While running the ```tabulo --help``` , I am encountering the following error. 
There seem to be a conflict between the two libraries, where each library want some specific version of ```click```.  I have downloaded both versions of click, i.e. 6.7 and 7.1.2. but still encountering error. 
```
Traceback (most recent call last):
  File "/home/gurjot/Tabulo/tabenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/gurjot/Tabulo/tabenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/gurjot/Tabulo/tabenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 6.7 (/home/gurjot/Tabulo/tabenv/lib/python3.8/site-packages), Requirement.parse('click>=7.1.2'), {'Flask'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gurjot/Tabulo/tabenv/bin/tabulo", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/gurjot/Tabulo/tabenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/gurjot/Tabulo/tabenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/gurjot/Tabulo/tabenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/gurjot/Tabulo/tabenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/gurjot/Tabulo/tabenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/gurjot/Tabulo/tabenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 6.7 (/home/gurjot/Tabulo/tabenv/lib/python3.8/site-packages), Requirement.parse('click>=7.1.2'), {'Flask'})
```

**Comment by marc-philipp-knechtle** [comment]
Hi, i had the same issue. This was caused by your python version using the latest available `Flask` package. 
(From your output, it's visible that you use `python3.8` which isn't supposed to be used anyway, I used `python3.6`). 
There is no upper bound in `setup.py` specified which is the reason why python installs the latest package.
I solved this issue by adding a concrete range to the `setup.py` file for click. In my case it was `Flask>=0.12,<2.0.0`.
I hope this solves your issue.
